# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WILVmBs0iwDCa6WbfJUTRGEzWMe13gvW
"""

# Import matplotlib
import matplotlib.pyplot as plt

# Line plot.
x = [1,2,3,4,5]
y = [10,20,25,30,40]

plt.plot(x,y)

plt.xlabel('This is X-Label')
plt.ylabel('This is Y-Label')
plt.title('This is our first Line Plot')

plt.show()

from matplotlib import color_sequences
plt.figure(figsize=(6,4))

x = [1,2,3,4,5]
y1 = [1,4,9,16,25]
y2 = [1,2,3,4,5]

# Line 1 plot
plt.plot(x , y1 , label = 'Line 1', color = 'green')
plt.plot(x , y2 , label = 'Line 2', color = 'red')

plt.legend()
plt.grid()

import matplotlib.pyplot as plt
import numpy as np

# Data
x = [1, 2, 3, 4, 5]
y = [5, 7, 4, 6, 8]
nums = np.random.randn(100)

plt.figure(figsize=(12,4))

# 1. Scatter
plt.subplot(1,3,1)
plt.scatter(x, y, color="red")
plt.title("Scatter")

# 2. Histogram
plt.subplot(1,3,2)
plt.hist(nums, bins=10, color="skyblue")
plt.title("Histogram")

# 3. Boxplot
plt.subplot(1,3,3)
plt.boxplot(nums)
plt.title("Boxplot")

plt.tight_layout()
plt.show()

# Subplots

x = [1, 2, 3, 4, 5]
y1 = [1, 4, 9, 16, 25]
y2 = [1, 2, 3, 4, 5]

plt.subplot(2,2,1)
plt.plot(x,y1,'v--')
plt.title('Plot 1')

plt.subplot(2,2,4)
plt.plot(x,y2,'g--')
plt.title('Plot 2')

plt.tight_layout()
plt.show()

# Object-Oriented Interface

# Sample data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# Step 1: Create a Figure (canvas)
fig = plt.figure(figsize=(6,4))

# Step 2: Add Axes (x0, y0, width, height) in 0-1 range
ax = fig.add_axes([0.1, 0.1, 0.8, 0.8])

# Step 3: Plot data on the Axes
ax.plot(x, y, color="purple", marker="o", linestyle="-")

# Step 4: Customize
ax.set_title("Object-Oriented Plot")
ax.set_xlabel("X-axis")
ax.set_ylabel("Y-axis")
ax.grid(True)

plt.show()

# Multiple / Inset Axes

# Sample data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

fig = plt.figure(figsize=(6,4))
ax1 = fig.add_axes([0.1,0.1,0.8,0.8])   # [left, bottom, width, height]
ax1.plot(x,y)
plt.title('Mera Phone')

ax2 = fig.add_axes([0.2,0.5,0.3,0.3])
ax2.plot(x,y)
plt.title('Remote')

plt.show()

# Figure Size , Aspect Ratio & DPI

x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

plt.figure(figsize=(6,4),dpi=100)   # dpi -> Controls zoom-in or zoom-out for a graph
plt.plot(x,y)
plt.grid()

x = [1, 2, 3, 4, 5]
y1 = [2, 4, 6, 8, 10]
y2 = [1, 3, 5, 7, 9]

plt.plot(x,y1,label='Line 1',color='green',lw=2,ls=':',marker='*')
plt.plot(x,y2,label='Line 2',color='red',lw=1,ls='-.',marker='+')

plt.legend()
plt.grid()

x = [1, 2, 3, 4, 5]
y = [5, 7, 4, 6, 8]

# Scatter Plot -> 2 Columns/Variables/Features
plt.scatter(x,y)
plt.show()

# Hisplot -> Shows spread of only one column/variable
import numpy as np
nums = np.random.randn(100)
plt.hist(nums,bins=20)

# Box Plot -> Shows outliers of a single column

plt.boxplot(nums)

# Min
# 25% -> Lower Quartile
# 50% -> Median
# 75% -> Upper Quartile
# Max

# Values between Lower & Upper Quartiles are Generic or Actual values

# Value outside of Lower & Upper Quartile are considered to be Outliers.

