# -*- coding: utf-8 -*-
"""Seaborn_class3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XqffJIRn-EevV-Ifig7HnyEwMnkMa_n-

# Seaborn – Class 3: Distribution Plots

## What Are Distribution Plots?

Distribution plots show how data values are **spread or concentrated**.

Seaborn offers:
- **`histplot()`** → modern histogram (with optional KDE)
- **`kdeplot()`** → smooth curve of distribution
- **`rugplot()`** → small marks showing individual values  
*(Older `distplot()` is now replaced by `histplot()`.)*

## histplot() – Basic Histogram
"""

import seaborn as sns
tips = sns.load_dataset('tips')
sns.histplot(x=tips['total_bill'], kde=True)  # Kernel Density Estimate

"""## kdeplot() – Kernel Density Estimate"""

from numpy import true_divide
sns.kdeplot(x=tips['total_bill'], fill=True, color='black')

"""## distplot() (Legacy) vs histplot()

> `distplot()` is deprecated.
> Use `histplot()` or `kdeplot()` instead.

## rugplot() – Small Ticks for Observations
"""

sns.rugplot(x=tips['total_bill'])

"""## Multiple Distributions with hue"""

sns.histplot(x=tips['total_bill'], hue=tips['time'])  # hue -> woh column jisme categories aa rhi ho.

"""Key takeaways

histplot() → flexible histogram (can combine with KDE).

kdeplot() → smooth density curve.

rugplot() → quick look at raw values.

distplot() is deprecated → prefer histplot().

Use hue to compare groups in the same distribution plot.
"""

# 1.) Histogram on Left and KDE plot on Right tips distribution.
import matplotlib.pyplot as plt
plt.subplot(1, 2, 1)
sns.histplot(x=tips['tip'])
plt.subplot(1, 2, 2)
sns.kdeplot(x=tips['tip'])

# 2.) show the distribution of size column but as bell shaped curve.
sns.kdeplot(x=tips['size'])

iris = sns.load_dataset('iris')
iris

# 3.) Distribution of sepal length grouping by species.
sns.histplot(x=iris['sepal_length'], hue=iris['species'])

# 4.) Make a plot showing distribution of petal length.
sns.histplot(x=iris['petal_length'])