# -*- coding: utf-8 -*-
"""Seaborn_class1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NW7M24S_NPKYqBnBvY0ZVYaMS_XYqbka

#  Seaborn – Class 1: Introduction & Relational Plots

## What is Seaborn?

Seaborn is a **high-level data visualization library** built on top of Matplotlib.  
It provides:
- Beautiful, modern default styles  
- Concise syntax (less code for complex visuals)  
- Integration with Pandas DataFrames  

Perfect for quick, attractive plots while keeping full Matplotlib power underneath.

###  What Are Relational Plots?

Relational plots are used to **show the relationship between two variables**.

- They focus on how one variable changes with respect to another.
- Typically used for continuous (numeric) data, but can also mix with categories.

In Seaborn, the main relational plots are:

1. **`scatterplot()`** → displays individual data points  
2. **`lineplot()`** → shows a continuous trend or summary line

> Both functions belong to Seaborn’s *relational* family.

## You can load sample DataSets using SNS
"""

import seaborn as sns
df = sns.load_dataset('tips')
df2 = sns.load_dataset('iris')
df

"""### Scatter Plot with scatterplot()"""

sns.scatterplot(x=df['total_bill'], y=df['tip'], hue=df['sex'])

"""### Line Plot with lineplot()"""

sns.lineplot(x=df['total_bill'], y=df['tip'], hue=df['sex'])

"""### Styling & Color Palettes"""



