# -*- coding: utf-8 -*-
"""Seaborn_class2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4wVzRoF9aLDOc23pYHaepDEm1BvpEJp

# Seaborn – Class 2: Categorical Plots

## What Are Categorical Plots?

Categorical plots visualize data where at least one variable is **categorical**  
(e.g., day of week, gender, class).

Seaborn gives several easy options to:
- Compare **counts** or **averages** across categories
- Understand spread & distribution

## barplot() vs countplot()
"""

import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset('tips')

sns.barplot(x=tips['day'], y=tips['total_bill'])

sns.countplot(x=tips['sex'])    # Mostly used in Machine Learning for class Imbalance.

"""## boxplot()"""

sns.boxplot(x=tips['sex'], y=tips['total_bill'])

"""## stripplot() & swarmplot()"""

sns.stripplot(x=tips['day'], y=tips['total_bill'])

sns.swarmplot(x=tips['day'], y=tips['total_bill'])

"""| Plot        | Best for |
|-------------|-----------|
| **barplot** | Compare average values across categories |
| **countplot** | Show how many items fall in each category |
| **boxplot** | See median, quartiles, and outliers |
| **violinplot** | Same as boxplot + shows distribution |
| **stripplot** | View every observation (good for small data) |
| **swarmplot** | Like stripplot but avoids overlap |

"""

# 1. How many smokers V/S Non smokers group by Gender
sns.countplot(x=tips['smoker'], hue=tips['sex'])

# 2. Average total bill according to smoker
sns.barplot(x=tips['smoker'],y=tips['total_bill'])

# 3. Average tip by day, group by time
sns.barplot(x=tips['day'], y=tips['tip'], hue=tips['time'])

# 4. Spread of total bill accross days
sns.boxplot(x=tips['day'],y=tips['total_bill'])

# 5. tip distribution by smoker , group by gender.
sns.boxplot(x=tips['smoker'], y=tips['tip'], hue=tips['sex'])
# OR
#sns.boxplot(x=tips['smoker'], y=tips['tip'], hue=tips['sex'])