# -*- coding: utf-8 -*-
"""Seaborn_class4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15aald3fzg8Aya6cGoxBr7PR0BfkmZ1Rf

# Seaborn – Class 4: Regression & Mixed Plots

## Regression & Mixed Plots

Seaborn provides plots that combine **relationships** and **statistical models** or mix multiple plot types.

- `regplot()` / `lmplot()` → scatter + regression line  
- `jointplot()` → scatter with hist/KDE  
- `pairplot()` → multiple relationships in one go

# regplot() – Scatter + Regression Line
"""

import seaborn as sns

tips = sns.load_dataset('tips')

sns.regplot(x=tips['total_bill'], y=tips['tip'])

"""# lmplot() – Regression with Facets"""

sns.lmplot(x='total_bill', y='tip', data=tips)

"""# jointplot() – Scatter + Histogram / KDE"""

sns.jointplot(data=tips, x='total_bill', y='tip', kind='kde')

"""# pairplot() – Relationships Between Many Variables"""

sns.pairplot(tips)

"""# **heatmap()**"""

sns.heatmap(tips.corr(numeric_only=True), annot=True)

iris = sns.load_dataset('iris')

sns.heatmap(iris.corr(numeric_only=True), annot=True)

"""# clustermap()"""

sns.clustermap(iris.corr(numeric_only=True), annot=True)





