# -*- coding: utf-8 -*-
"""seaborn_assingment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRyFlRYxTd8ImzDdhzCTmsuyNjWVFhUl

# Superstore Sales Assignment
Dataset: Sample Superstore (Kaggle)

Topics: Pandas + Matplotlib + Seaborn

## Part A - Pandas Basics

### Q1. Import pandas and load the dataset.
"""

import pandas as pd
df = pd.read_csv('Superstore.csv', encoding='latin1')

"""### Q2. Display first 10 rows."""

df.head(10)

"""### Q3. Display last 10 rows."""

df.tail(10)

"""### Q4. Print shape and column names."""

df.shape

"""### Q5. Use info()."""

df.info()

"""### Q6. Use describe()."""

df.describe()

"""### Q7. Check missing values."""

df.isnull().sum()

"""### Q8. Check duplicate rows."""

df.duplicated().sum()

"""### Q9. Remove duplicate rows."""

df.drop_duplicates(inplace=True)

df.duplicated().sum()

"""### Q10. Convert Order Date to datetime."""

df['Order Date'] = pd.to_datetime(df['Order Date'])
df.dtypes

"""### Q11. Convert Ship Date to datetime."""

df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df.dtypes

"""### Q12. Find total Sales."""

print(f'Total sales :- {df['Sales'].sum()}')

"""### Q13. Find total Profit."""

print(f'Total profit :- {df['Profit'].sum()}')

"""### Q14. Find average Discount."""

print(f'Average discount :- {df['Discount'].mean()}')

"""### Q15. Find highest Sales order."""

df[df['Sales'] == df['Sales'].max()]

"""### Q16. Find lowest Profit order."""

df[df['Profit'] == df['Profit'].min()]

"""### Q17. Category-wise total Sales."""

df.groupby('Category')['Sales'].sum()

"""### Q18. Region-wise total Profit."""

df.groupby('Region')['Profit'].sum()

"""### Q19. Top 10 customers by Sales."""

df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)

"""### Q20. Save the cleaned dataset as clean_superstore.csv."""

# df.to_csv('clean_superstore.csv')

"""## Part B - Data Analysis

### Q21. Find Segment-wise Sales.
"""

df.groupby('Segment')['Sales'].sum()

"""### Q22. Find State-wise Sales."""

df.groupby('State')['Sales'].sum()

"""### Q23. Find Top 5 States by Profit."""

df.groupby('State')['Profit'].sum().sort_values(ascending=False).head(5)

"""### Q24. Find Top 10 Products by Sales."""

df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)

"""### Q25. Find the most profitable Sub-Category."""

df.groupby('Sub-Category')['Profit'].sum().sort_values(ascending=False).head(1)

"""### Q26. Find average Sales by Region."""

df.groupby('Region')['Sales'].mean()

"""### Q27. Find total Quantity sold by Category."""

df.groupby('Category')['Quantity'].sum()

"""### Q28. Display orders from the West Region."""

df.groupby('Region').get_group('West')

"""### Q29. Display Technology category orders."""

df.groupby('Category').get_group('Technology')

"""### Q30. Find monthly Sales trend."""

df.groupby(df['Order Date'].dt.month)['Sales'].sum()

"""## Part C - Matplotlib

### Q31. Create a Bar Chart of Category-wise Sales.
"""

import matplotlib.pyplot as plt
df.groupby('Category')['Sales'].sum().plot(kind='bar')
plt.title('Category-wise Sales')
plt.xlabel('Category')
plt.ylabel('Sales')
plt.show()

"""### Q32. Create a Pie Chart of Segment distribution."""

df.groupby('Segment')['Sales'].sum().plot(kind='pie')
plt.title('Segment distribution')
plt.show()

"""### Q33. Create a Histogram of Sales."""

df['Sales'].plot(kind='hist')
plt.title('Sales')
plt.show()

"""### Q34. Create a Line Chart of monthly Sales."""

df.groupby(df['Order Date'].dt.month)['Sales'].sum().plot(kind='line')
plt.title('Monthly Sales')
plt.show()

"""### Q35. Create a Scatter Plot of Sales vs Profit."""

plt.scatter(df['Sales'],df['Profit'])
plt.title('Sales vs Profit')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.show()

"""### Q36. Create a Box Plot of Profit."""

plt.boxplot(df['Profit'])
plt.title('Profit')
plt.show()

"""### Q37. Create a Horizontal Bar Chart of Top 10 States by Sales."""

df.groupby('State')['Sales'].sum().sort_values(ascending=False).head(10).plot(kind='barh')
plt.title('Top 10 States by Sales')
plt.gca().invert_yaxis()
plt.show()

"""## Part D - Seaborn

### Q38. Create a Count Plot of Category.
"""

import seaborn as sns
sns.countplot(data=df , x='Category')
plt.title('Category')
plt.show()

"""### Q39. Create a Bar Plot of Profit by Region."""

sns.barplot(data=df , x='Region' , y='Profit')
plt.title('Profit by Region')
plt.show()

"""### Q40. Create a Box Plot of Sales by Segment."""

sns.boxplot(data=df , x='Segment' , y='Sales')

plt.title('Sales by Segment')
plt.xlabel('Segment')
plt.ylabel('Sales')

plt.show()

"""### Q41. Create a Strip Plot of Sales by Category."""

sns.stripplot(data=df , x='Category' , y='Sales')

plt.title('Sales by Category')
plt.xlabel('Category')
plt.ylabel('Sales')

plt.show()

"""### Q42. Create a Swarm Plot of Profit by Category."""

# sns.swarmplot(data=df , x='Category' , y='Profit' , size=1)

# plt.title('Profit by Category')
# plt.xlabel('Category')
# plt.ylabel('Profit')

# plt.show()
""" Taking too much time to run """

"""### Q43. Create a Heatmap of numeric columns."""

numeric_df = df.select_dtypes(include='number')

sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.show()

"""### Q44. Create a Pairplot for numeric columns."""

sns.pairplot(df)
plt.show()

"""### Q45. Create a Histogram with KDE for Sales."""

sns.histplot(data=df , x='Sales' , kde=True)
plt.title('Sales')
plt.show()